### PR TITLE
Implement coverage reporting for frontend Cypress tests

### PR DESCRIPTION
**Pull request by dominiquecuevas**
Our code needs to be "instrumented" or inserted with counters to get a coverage report from Cypress tests. 
Using the _Instanbul_ library to instrument and the _Cypress Code Coverage_ plugin to generate the coverage report.  

After running Cypress tests, get the coverage report possible in 3 views:

1. Report summary in the terminal
image

2. Report in the terminal 
image

3. Browser view 
image
image

### CODE REVIEW

**Review by athelia — APPROVED** [review]
Nicely done! This probably took more research than is visible here in the PR. There are some really nice ways to view the coverage output that are very readable.

For the utilities file with the missing coverage, do you have a clear sense of how you want to test it or should we meet (e.g. to talk about mocks)? 

It's also interesting that it's showing branch testing coverage - I'd be interested to know more about how that works when we meet next.

**Comment by dominiquecuevas** [comment]
> Nicely done! This probably took more research than is visible here in the PR. There are some really nice ways to view the coverage output that are very readable.
> 
> For the utilities file with the missing coverage, do you have a clear sense of how you want to test it or should we meet (e.g. to talk about mocks)?
> 
> It's also interesting that it's showing branch testing coverage - I'd be interested to know more about how that works when we meet next.

@athelia for the utility function, I'm thinking it's one-off and excluding it from test coverage reports. `getApiHostname()` chooses the endpoint depending on development/production environment. One-off because we just test development. I would like to know everyone's thoughts though and would like to discuss in the next meeting.

**Review by aileentran — APPROVED** [review]
Nice configs. Looks good to me!

**Comment by dominiquecuevas** [comment]
> > Nicely done! This probably took more research than is visible here in the PR. There are some really nice ways to view the coverage output that are very readable.
> > For the utilities file with the missing coverage, do you have a clear sense of how you want to test it or should we meet (e.g. to talk about mocks)?
> > It's also interesting that it's showing branch testing coverage - I'd be interested to know more about how that works when we meet next.
> 
> @athelia for the utility function, I'm thinking it's one-off and excluding it from test coverage reports. `getApiHostname()` chooses the endpoint depending on development/production environment. One-off because we just test development. I would like to know everyone's thoughts though and would like to discuss in the next meeting.

The fix may be a config setting in Next.js to switch to the correct api depending whether the app runs in production/development

**Pull request merged**
